// GitHub Git Data API — native fetch only (Octokit bundles poorly in CF Workers)

const GH_API = 'https://api.github.com';
const GH_API_VERSION = '2022-11-28';

interface GitBlobResponse { sha: string }
interface GitTreeResponse { sha: string }
interface GitCommitResponse { sha: string }
interface GitRefResponse { object: { sha: string } }
interface AuthUserResponse { login: string }

function ghHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': GH_API_VERSION,
    'Content-Type': 'application/json',
    'User-Agent': 'bymamstudio-deploy-platform/1.0',
  };
}

async function ghFetch(token: string, path: string, init?: RequestInit): Promise<Response> {
  return fetch(`${GH_API}${path}`, {
    ...init,
    headers: { ...ghHeaders(token), ...(init?.headers as Record<string, string> | undefined) },
  });
}

function toBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

/**
 * Create the repo `mam-{siteId}` under `owner` (user or org).
 * No-ops if the repo already exists.
 */
export async function ensureGithubRepo(
  token: string,
  owner: string,
  repoName: string,
): Promise<void> {
  // Check existence first
  const check = await ghFetch(token, `/repos/${owner}/${repoName}`);
  if (check.ok) return;

  // Determine whether owner is the authenticated user or an org
  const meRes = await ghFetch(token, '/user');
  const me = await meRes.json() as AuthUserResponse;
  const isUserRepo = me.login.toLowerCase() === owner.toLowerCase();

  const endpoint = isUserRepo ? '/user/repos' : `/orgs/${owner}/repos`;
  const createRes = await ghFetch(token, endpoint, {
    method: 'POST',
    body: JSON.stringify({
      name: repoName,
      private: true,
      auto_init: false,
      description: 'Generated by By MAM Studio Deploy Platform',
    }),
  });

  if (!createRes.ok) {
    throw new Error(`GitHub repo creation failed: ${await createRes.text()}`);
  }
}

export interface GitFile {
  path: string;
  content: Uint8Array;
}

/**
 * Push `files` to `owner/repo` on the `main` branch.
 * Handles both initial commits (no branch yet) and re-deploys (force-update).
 * Returns the new commit SHA.
 */
export async function pushFilesToRepo(
  token: string,
  owner: string,
  repo: string,
  files: GitFile[],
  message: string,
): Promise<string> {
  // 1. Find existing HEAD (undefined if repo is empty / branch doesn't exist yet)
  const refRes = await ghFetch(token, `/repos/${owner}/${repo}/git/refs/heads/main`);
  const existingCommitSha = refRes.ok
    ? (await refRes.json() as GitRefResponse).object.sha
    : undefined;

  // 2. Create a blob for every file (all base64-encoded)
  const treeItems = await Promise.all(
    files.map(async (file) => {
      const blobRes = await ghFetch(token, `/repos/${owner}/${repo}/git/blobs`, {
        method: 'POST',
        body: JSON.stringify({ content: toBase64(file.content), encoding: 'base64' }),
      });
      if (!blobRes.ok) {
        throw new Error(`Blob creation failed for "${file.path}": ${await blobRes.text()}`);
      }
      const blob = await blobRes.json() as GitBlobResponse;
      return {
        path: file.path,
        mode: '100644' as const,
        type: 'blob' as const,
        sha: blob.sha,
      };
    }),
  );

  // 3. Create tree (no base_tree — we replace the entire tree each deploy)
  const treeRes = await ghFetch(token, `/repos/${owner}/${repo}/git/trees`, {
    method: 'POST',
    body: JSON.stringify({ tree: treeItems }),
  });
  if (!treeRes.ok) throw new Error(`Tree creation failed: ${await treeRes.text()}`);
  const tree = await treeRes.json() as GitTreeResponse;

  // 4. Create commit
  const commitBody: Record<string, unknown> = { message, tree: tree.sha, parents: [] };
  if (existingCommitSha) commitBody.parents = [existingCommitSha];

  const commitRes = await ghFetch(token, `/repos/${owner}/${repo}/git/commits`, {
    method: 'POST',
    body: JSON.stringify(commitBody),
  });
  if (!commitRes.ok) throw new Error(`Commit creation failed: ${await commitRes.text()}`);
  const commit = await commitRes.json() as GitCommitResponse;

  // 5. Create or force-update the main branch reference
  if (existingCommitSha) {
    const patchRes = await ghFetch(token, `/repos/${owner}/${repo}/git/refs/heads/main`, {
      method: 'PATCH',
      body: JSON.stringify({ sha: commit.sha, force: true }),
    });
    if (!patchRes.ok) throw new Error(`Ref update failed: ${await patchRes.text()}`);
  } else {
    const createRes = await ghFetch(token, `/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      body: JSON.stringify({ ref: 'refs/heads/main', sha: commit.sha }),
    });
    if (!createRes.ok) throw new Error(`Ref creation failed: ${await createRes.text()}`);
  }

  return commit.sha;
}
